language: node_js
node_js:
  - '8'
notifications:
  email: false
before_install:
  - npm install codecov -g
after_success:
  - codecov
before_deploy:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token: $GITHUB_TOKEN
